name: Continuous Integration
on: [pull_request, push]
jobs:
  build:
    name: Build
    runs-on: ${{matrix.runs-on}}
    strategy:
      matrix:
        target: [macOS, Windows]
        include:
          - target: macOS
            runs-on: macos-14
            rust-toolchains: x86_64-apple-darwin
          - target: Windows
            runs-on: windows-2022
            rust-toolchains: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
